/**
 * Writes frontend/config.js from API_BASE_URL (Vercel build env var).
 */
const fs = require("fs");
const path = require("path");

const apiBaseUrl = (process.env.API_BASE_URL || "").trim().replace(/\/$/, "");
const target = path.join(__dirname, "..", "config.js");
const contents = [
  "// Auto-generated by frontend/scripts/generate-config.js — do not edit.",
  `window.__API_BASE_URL__ = ${JSON.stringify(apiBaseUrl)};`,
  "",
].join("\n");

fs.writeFileSync(target, contents, "utf8");

if (!apiBaseUrl) {
  console.warn(
    "Warning: API_BASE_URL is not set. Production users must set it in Vercel env vars.",
  );
} else {
  console.log(`Wrote ${target} with API_BASE_URL=${apiBaseUrl}`);
}
