/**
 * Writes ui/config.js from the API_BASE_URL environment variable.
 * Used by Vercel at build time to point the static UI at the Railway API.
 */
const fs = require("fs");
const path = require("path");

const apiBaseUrl = (process.env.API_BASE_URL || "").trim().replace(/\/$/, "");
const target = path.join(__dirname, "..", "ui", "config.js");
const contents = [
  "// Auto-generated by scripts/generate_ui_config.js — do not edit.",
  `window.__API_BASE_URL__ = ${JSON.stringify(apiBaseUrl)};`,
  "",
].join("\n");

fs.writeFileSync(target, contents, "utf8");

if (!apiBaseUrl) {
  console.warn(
    "Warning: API_BASE_URL is not set. The UI will fall back to http://127.0.0.1:8000 in local dev only.",
  );
} else {
  console.log(`Wrote ${target} with API_BASE_URL=${apiBaseUrl}`);
}
